# Generated by Django 3.2.7 on 2021-09-29 20:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('Name', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=50)),
                ('Feedback', models.TextField()),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
